-- Generated by nwg-displays on 2026-06-04 at 20:09:35. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@59.98",
    position = "0x0",
    scale = 1.5000000000000004
})
